# Generated by Django 4.0.4 on 2022-05-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_hashed_password_user_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, height_field=100, null=True, upload_to='profile_pics', width_field=100),
        ),
    ]
