# Generated by Django 4.0.4 on 2022-05-01 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_soldarticle_article_remove_soldarticle_buyer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='condition',
            field=models.CharField(choices=[('New', 'New'), ('Used', 'Used')], default='New', max_length=10),
        ),
    ]
