# Generated by Django 4.0.4 on 2022-05-01 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_category_created_by_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
        migrations.AlterField(
            model_name='article',
            name='seller',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
    ]
