# Generated by Django 4.0.4 on 2022-05-02 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_article_city_user_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(max_length=50),
        ),
    ]
