# Generated by Django 4.0.4 on 2022-06-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_article_city_alter_user_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='article',
            name='city',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Marrakech', 'Marrakech'), ('Fes', 'Fes'), ('Tanger', 'Tanger'), ('Oujda', 'Oujda'), ('Agadir', 'Agadir'), ('Tetouan', 'Tetouan'), ('Meknes', 'Meknes'), ('Safi', 'Safi'), ('El Jadida', 'El Jadida'), ('Khouribga', 'Khouribga'), ('Ouarzazate', 'Ouarzazate'), ('Settat', 'Settat'), ('Sidi Kacem', 'Sidi Kacem'), ('Kenitra', 'Kenitra'), ('Taza', 'Taza'), ('Tiznit', 'Tiznit'), ('Sidi Ifni', 'Sidi Ifni')], max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='city',
            field=models.CharField(choices=[('Casablanca', 'Casablanca'), ('Rabat', 'Rabat'), ('Marrakech', 'Marrakech'), ('Fes', 'Fes'), ('Tanger', 'Tanger'), ('Oujda', 'Oujda'), ('Agadir', 'Agadir'), ('Tetouan', 'Tetouan'), ('Meknes', 'Meknes'), ('Safi', 'Safi'), ('El Jadida', 'El Jadida'), ('Khouribga', 'Khouribga'), ('Ouarzazate', 'Ouarzazate'), ('Settat', 'Settat'), ('Sidi Kacem', 'Sidi Kacem'), ('Kenitra', 'Kenitra'), ('Taza', 'Taza'), ('Tiznit', 'Tiznit'), ('Sidi Ifni', 'Sidi Ifni')], max_length=50),
        ),
    ]
